image: sikalabs/ci

stages:
  - build

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --platform linux/amd64 -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
